version: '3'
services:
    apinode:
        build: '.'
        container_name: apinode
        links:
            - mongo
        ports:
            - "8000:8000"
        volumes:
            - ".:/usr/src/app"
        networks:
            - app-network

    mongo:
        image: mongo:4.4-focal
        container_name: mongo
        networks:
            - app-network

networks:
    app-network:
        driver: bridge