version: '3'
services:
    apinode:
        build: '.'
        container_name: apinode
        links:
            - mysqldb
        ports:
            - "8000:8000"
        volumes:
            - ".:/usr/src/app"
            - "/usr/src/app/node_modules"
        networks:
            - app-network

    mongodb:
        image: mongo:5.0.3-focal
        container_name: mongodb
        networks:
            - app-network

networks:
    app-network:
        driver: bridge